1568889681168	Sync.LogManager	DEBUG	Flushing file log
1568889681170	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://profile.accounts.firefox.com/v1/profile
1568889681170	Services.Common.RESTRequest	TRACE	Channel for GET https://profile.accounts.firefox.com/v1/profile returned status code 2152398878
1568889681170	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1568889681170	Services.Common.RESTRequest	TRACE	GET body: 
1568889681171	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 487\"  data: no]"}
1568889681183	Sync.LogManager	DEBUG	Log cleanup threshold time: 1568025681183
1568889681262	Sync.LogManager	DEBUG	Done deleting files.
1568889682124	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1568889684112	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1568889833037	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1568889833038	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1568889833055	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1568889834036	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1568889843477	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1568889843477	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1568889843490	Sync.Service	DEBUG	User-Agent: Firefox/69.0 (Linux x86_64) FxSync/1.71.0.20190827005903.desktop
1568889843490	Sync.Service	INFO	Starting sync at 2019-09-19 16:44:03 in browser session N8nDsAdqyTok
1568889843491	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1568889843500	Sync.Status	INFO	Resetting Status.
1568889843501	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1568889843504	Sync.BrowserIDManager	INFO	Getting keys
1568889843505	Sync.BrowserIDManager	INFO	Getting an assertion from: https://token.services.mozilla.com/1.0/sync/1.5
1568889843505	FirefoxAccounts	DEBUG	enter getAssertion()
1568889843506	FirefoxAccounts	DEBUG	getKeypairAndCertificate: already have keyPair and certificate
1568889843506	FirefoxAccounts	DEBUG	getAssertionFromCert
1568889843509	FirefoxAccounts	DEBUG	getAssertionFromCert returning signed: true
1568889843510	Sync.BrowserIDManager	DEBUG	Getting a token
1568889843510	Services.Common.TokenServerClient	DEBUG	Beginning BID assertion exchange: https://token.services.mozilla.com/1.0/sync/1.5
1568889843511	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1568889843511	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1568889843511	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1568889843511	Services.Common.RESTRequest	TRACE	HTTP Header x-client-state: ***** (suppressed)
1568889843516	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://token.services.mozilla.com/1.0/sync/1.5
1568889843517	Services.Common.RESTRequest	TRACE	Channel for GET https://token.services.mozilla.com/1.0/sync/1.5 returned status code 2152398878
1568889843517	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1568889843517	Services.Common.RESTRequest	TRACE	GET body: 
1568889843517	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:246:13
1568889843518	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1568889843518	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1568889843518	Sync.BrowserIDManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
getTokenFromBrowserIDAssertion@tokenserverclient.js:246:13
1568889843521	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1568889843521	FirefoxAccounts	DEBUG	getOAuthToken enter
1568889843523	FirefoxAccounts	TRACE	getCachedToken returning cached token
1568889843523	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1568889843524	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1568889843524	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1568889843524	Services.Common.RESTRequest	TRACE	HTTP Header accept: application/json
1568889843524	Services.Common.RESTRequest	TRACE	HTTP Header if-none-match: "e6f3275e0bba161c5d7eae737440da2154da014f-gzip"
1568889843528	Sync.Resource	WARN	GET request to https://sync-612-us-west-2.sync.services.mozilla.com/1.5/97000915/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1568889843528	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1568889843529	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1568889843529	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1568889843530	Sync.SyncScheduler	DEBUG	Sync error count has exceeded 3; enforcing backoff.
1568889843530	Sync.SyncScheduler	DEBUG	Starting client-initiated backoff. Next sync in 5388812 ms.
1568889843530	Sync.SyncScheduler	DEBUG	Next sync in 5388812 ms. (why=client-backoff-schedule)
1568889843535	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
